-- ============================================================
-- FCS DocHub — Database schema
-- Run this in phpMyAdmin (cPanel) after creating the database
-- ============================================================

SET NAMES utf8mb4;

CREATE TABLE users (
  id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email         VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name     VARCHAR(120) NOT NULL,
  role          ENUM('admin','editor','viewer') NOT NULL DEFAULT 'viewer',
  is_active     TINYINT(1) NOT NULL DEFAULT 1,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login    TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE folders (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name       VARCHAR(120) NOT NULL UNIQUE,
  sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE documents (
  id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  folder_id     INT UNSIGNED NOT NULL,
  display_name  VARCHAR(255) NOT NULL,          -- name shown to users
  stored_name   VARCHAR(64)  NOT NULL UNIQUE,   -- random filename on disk
  mime_type     VARCHAR(120) NOT NULL,
  file_ext      VARCHAR(10)  NOT NULL,
  size_bytes    BIGINT UNSIGNED NOT NULL,
  uploaded_by   INT UNSIGNED NOT NULL,
  uploaded_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (folder_id)   REFERENCES folders(id),
  FOREIGN KEY (uploaded_by) REFERENCES users(id),
  INDEX idx_folder (folder_id),
  INDEX idx_name (display_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Optional: audit trail of who did what
CREATE TABLE activity_log (
  id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id    INT UNSIGNED NOT NULL,
  action     VARCHAR(30) NOT NULL,   -- login, upload, download, rename, delete
  detail     VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  INDEX idx_user_time (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- Seed data ----------
INSERT INTO folders (name, sort_order) VALUES
  ('Policies', 1),
  ('Forms', 2),
  ('HR', 3),
  ('Board documents', 4),
  ('Images', 5);

-- User accounts are NOT seeded here because password hashes must be
-- generated by PHP. After importing this file, browse to setup.php
-- once — it creates the initial admin/editor/viewer accounts with
-- proper bcrypt hashes. Then DELETE setup.php from the server.
